<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<?php $_formMessage=$this->getPartialAuthorizationFormMessage(); ?>
<?php $_isPartialAuthorization=$this->isPartialAuthorization(); ?>
<?php if ($_isPartialAuthorization || $_formMessage): ?>
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>_before" style="display:none;">
    <?php if ($_formMessage): ?>
    <?php echo $this->showNoticeMessage($_formMessage) ?>
    <?php endif;?>

    <?php if ($this->isPartialAuthorization()): ?>
        <?php echo $this->getChildHtml('cards') ?>
        <div class="release-amounts">
            <div class="pretty medium info btn"><button class="button" type="button" id="payment-button-cancel">Cancel</button></div>
            <span><?php echo $this->__('To cancel pending authorizations and release amounts that have already been processed during this payment, click Cancel.') ?></span>
        </div>
        <?php echo $this->showNoticeMessage($this->__('Please enter another credit card number to complete your purchase.')) ?>

        <script type="text/javascript">
        //<![CDATA[
        var cancelButtonId = 'payment-button-cancel';
        var cancelButton = $(cancelButtonId);
        cancelButton.click = null;
        Event.observe(cancelButton, 'click', cancelPaymentAuthorizations);

        function cancelPaymentAuthorizations(event, hideConfirm){
            if (!hideConfirm && !confirm('<?php echo $this->getCancelConfirmationMessage() ?>')) {
                return;
            }
            $('cancel-please-wait').show();
            new Ajax.Request('<?php echo $this->getCancelUrl() ?>', {
                onSuccess : function(transport) {
                    $('cancel-please-wait').hide();
                    try{
                        response = eval('(' + transport.responseText + ')');
                    } catch (e) {
                        response = {};
                    }
                    if (response.success) {
                        $(cancelButtonId).remove();
                        $('checkout-payment-method-load').update(response.update_html);
                        if (checkout) {
                            checkout.reloadProgressBlock();
                        }
                    } else {
                        var msg = response.error_message;
                        if (msg) {
                            alert(msg);
                        }
                    }
                }
            });
        }

        <?php if ($_message=$this->getPartialAuthorizationConfirmationMessage()): ?>
            if (!confirm('<?php echo $_message ?>')) {
                cancelPaymentAuthorizations(true, true);
            }
        <?php endif;?>
        //]]>
        </script>
        <span id="cancel-please-wait" class="please-wait" style="display:none">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Processing...') ?>
        </span>
    <?php endif;?>
</div>
<?php endif;?>
<?php echo $this->getChildHtml('method_form_block') ?>
