<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<?php 
$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
?>
<?php if($_helper->getItemCount() > 0): ?>
    <div class="block block-list block-compare">
        <div class="block-title">
            <strong><span><?php echo $this->__('Compare Products') ?>
                <?php if($_helper->getItemCount() > 0): ?> 
                    <small><?php echo $this->__('(%d)', $_helper->getItemCount()) ?></small>
                <?php endif; ?>
            </span></strong>
        </div>
        <div class="block-content">
        <?php if($_helper->getItemCount() > 0): ?>
            <ol id="compare-items">
            <?php foreach($_items as $_index => $_item): ?>
                <li class="item">
                    <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
                    <a href="<?php echo $_helper->getRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the compare products?') ?>');"><i class="icon-cancel-squared"></i></a>
                    <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('compare-items')</script>
            <div class="actions">
                <a href="<?php echo $_helper->getClearListUrl() ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?>');"><?php echo $this->__('Clear All') ?></a>
                <div class="pretty small secondary btn icon-right icon-flow-parallel"><a href="#" title="<?php echo $this->__('Compare') ?>" class="link-compare" onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><?php echo $this->__('Compare') ?></a></div>
            </div>
        <?php else: ?>
            <p class="empty"><?php echo $this->__('You have no items to compare.') ?></p>
        <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
