<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('checkout.onepage.login.extra')?>
<div>
    <?php echo $this->getChildHtml('login_before')?>
    <div>
        <h3><?php echo $this->__('Login') ?></h3>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        <fieldset>
            <?php echo $this->getBlockHtml('formkey'); ?>
            <h4><?php echo $this->__('Already registered?') ?></h4>
            <p><?php echo $this->__('Please log in below:') ?></p>
            <ul class="form-list">
                <li class="field">
                    <?php /*
                    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    */ ?>
                    <input type="text" class="normal email input input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" placeholder="<?php echo $this->__('Email Address') ?>" />
                </li>
                <li class="field">
                    <?php /*
                    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                    */ ?>
                    <input type="password" class="normal password input input-text required-entry" id="login-password" name="login[password]" placeholder="<?php echo $this->__('Password') ?>" />
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </fieldset>
        </form>
        <div class="buttons-set">
            <?php /*
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            */ ?>
            <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
            <div class="pretty medium info btn f-right"><button type="submit" class="button" onclick="onepageLogin(this)" title="<?php echo $this->__('Login') ?>"><?php echo $this->__('Login') ?></button></div>
        </div>
    </div>    
    <div>
        <h3><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
        <?php /*
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
        <?php else: ?>
            <p><strong><?php echo $this->__('Register and save time!') ?></strong><br />
            <?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul>
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
        <?php endif; ?>
        */ ?>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <ul class="form-list">
                <li class="field control">
                    <label class="radio" for="login:register">
                        <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
                        <span></span><p><?php echo $this->__('Register and Checkout') ?></p>
                    </label>
                </li>                
                <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <li class="field control">
                    <label class="radio" for="login:guest">
                        <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" />
                        <span></span><p><?php echo $this->__('Checkout as Guest') ?></p>
                    </label>
                </li>
                <?php endif; ?>
            </ul>
            <?php /*
            <h4><?php echo $this->__('Register and save time!') ?></h4>
            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul class="ul">
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
            */ ?>
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>
        <div class="buttons-set">
            <div class="pretty secondary info btn f-right"><button type="button" class="button" onclick="checkout.setMethod();"><?php echo ($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?></button></div>
        </div>        
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
