<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
/* @var $this Mage_Sendfriend_Block_Send */
/**
 * Send to friend form
 *
 * @see Mage_Sendfriend_Block_Send
 */
?>
<script type="text/javascript">
//<![CDATA[
    i=0;
    var recipCount  = 1;
    var maxRecip    = <?php echo $this->getMaxRecipients() ?>;
    function remove_recipient(i){
        $('recipients_name'+i).up(2).remove();
        recipCount--;
        if(recipCount<maxRecip && maxRecip != 0) {
            $('add_recipient_button').show();
            $('max_recipient_message').hide();
        }
        return false;
    }

    function add_recipient(){
        ul = $('recipients_options');
        var li_mail = Element.extend(document.createElement("LI"));
        li_mail.addClassName('fields additional-row');
        li_mail.innerHTML = '<p><a href="delete_email" title="<?php echo $this->jsQuoteEscape($this->__('Remove Email')) ?>" onclick="remove_recipient('+i+'); return false" class="btn-remove"><i class="icon-cancel-squared"></i><?php echo $this->jsQuoteEscape($this->__('Remove Email')) ?><\/a><\/p>'
        li_mail.innerHTML += '<div class="field"><label for="recipients_name'+i+'" class="required inline"><?php echo $this->jsQuoteEscape($this->__('Name:')) ?><\/label><input name="recipients[name][]" type="text" class="input text normal input-text required-entry" id="recipients_name'+i+'" />';
        li_mail.innerHTML += '<div class="field"><label for="recipients_email'+i+'" class="required inline"><?php echo $this->jsQuoteEscape($this->__('Email:')) ?><\/label><input name="recipients[email][]" value="" title="<?php echo $this->jsQuoteEscape($this->__('Email Address')) ?>" id="recipients_email'+i+'" type="text" class="input text normal no-margin input-text required-entry validate-email" /><\/div>';
        i++;
        recipCount++;
        if(recipCount>=maxRecip && maxRecip != 0) {
            $('add_recipient_button').hide();
            $('max_recipient_message').show();
        }

        ul.appendChild(li_mail);
    }
//]]>
</script>

<div class="send-friend">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="page-title">
        <h1><?php echo $this->__('Email to a Friend') ?></h1>
    </div>
    <form action="<?php echo $this->getSendUrl() ?>" method="post" id="product_sendtofriend_form">
        <div class="fieldset">
            <?php echo $this->getBlockHtml('formkey')?>
            <h2 class="legend"><?php echo $this->__('Sender:') ?></h2>
            <ul class="form-list" id="sender_options">
                <li class="fields">
                    <div class="field">
                        <label for="sender_name" class="required inline"><?php echo $this->__('Name:') ?></label>
                        <input name="sender[name]" value="<?php echo $this->escapeHtml($this->getUserName()) ?>" title="<?php echo $this->__('Name') ?>" id="sender_name" type="text" class="text input normal input-text required-entry" />
                    </div>
                    <div class="field">
                       <label for="sender_email" class="required inline"><?php echo $this->__('Email:') ?></label>
                        <input name="sender[email]" value="<?php echo $this->escapeHtml($this->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" id="sender_email" type="text" class="text input normal input-text required-entry validate-email" />
                    </div>
                </li>
                <li class="wide field">
                    <?php /*
                    <label for="sender_message" class="required"><?php echo $this->__('Message:') ?></label>
                    */ ?>
                    <textarea name="sender[message]" class="input textarea wide input-text required-entry" id="sender_message" rows="3" placeholder="<?php echo $this->__('Message') ?>"><?php echo $this->escapeHtml($this->getMessage())?></textarea>
                </li>
            </ul>
        </div>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Recipient:') ?></h2>
            <ul class="form-list" id="recipients_options">
                <li class="fields">
                    <div class="field">
                        <label for="recipients_name" class="required inline"><?php echo $this->__('Name:') ?></label>
                        <input name="recipients[name][]" type="text" class="input text normal input-text required-entry" id="recipients_name" />
                    </div>
                    <div class="field">
                        <label for="recipients_email" class="required inline"><?php echo $this->__('Email:') ?></label>
                        <input name="recipients[email][]" value="" title="<?php echo $this->__('Email Address') ?>" id="recipients_email" type="text" class="input text normal no-margin input-text required-entry validate-email" />
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="back-link"><a href="#" onclick="history.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <div class="pretty medium secondary btn"><button type="submit" class="button<?php if (!$this->canSend()):?> disabled<?php endif ?>"<?php if (!$this->canSend()):?> disabled="disabled"<?php endif ?>><?php echo $this->__('Send Email') ?></button></div>
            <div id="max_recipient_message" style="display:none;">
                <?php if ($this->getMaxRecipients()): ?>
                  <p class="limit"><?php echo $this->__('Maximum %d email addresses allowed.', $this->getMaxRecipients()) ?></p>
                <?php endif; ?>
            </div>
            <?php if (1 < $this->getMaxRecipients()): ?>
                <p id="add_recipient_button">
                    <div class="pretty medium info btn"><button type="button" onclick="add_recipient();" class="button"><?php echo $this->__('Add Recipient') ?></button></div>
                </p>
            <?php endif; ?>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productSendtofriendForm = new VarienForm('product_sendtofriend_form');
        productSendtofriendForm.submit = function() {
            if(this.validator.validate()) {
                this.form.submit();
            }
        }.bind(productSendtofriendForm);
    //]]>
    </script>
</div>
