<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>

<?php
/**
 * Template for displaying product price at product view page, gift registry and wishlist
 *
 * @var $this Mage_Catalog_Block_Product_Price
 */
?>
<?php
    /** @var $_coreHelper Mage_Core_Helper_Data */
    $_coreHelper = $this->helper('core');
    /** @var $_catalogHelper Mage_Catalog_Helper_Data */
    $_catalogHelper = $this->helper('catalog');

    /** @var $_product Mage_Catalog_Model_Product */
    $_product = $this->getProduct();
    $_id = $_product->getId();
    $_msrpPrice = '';
    $priceElementIdPrefix = $this->getPriceElementIdPrefix() ? $this->getPriceElementIdPrefix() : 'product-price-';
?>
    <div class="price-box map-info">
    <?php $_price = $this->helper('tax')->getPrice($_product, $_product->getMsrp()) ?>
        <?php if($_product->getMsrp()): ?>
            <?php $_msrpPrice = $_coreHelper->currency($_product->getMsrp(),true,true) ?>
            <span class="old-price" ><?php echo $_msrpPrice ?></span>
        <?php endif; ?>

        <?php if ($_catalogHelper->isShowPriceOnGesture($_product)): ?>
            <?php $priceElementId = $priceElementIdPrefix . $_id . $this->getIdSuffix(); ?>
            <span id="<?php echo $priceElementId ?>" style="display:none"></span>
            <?php $popupId = 'msrp-popup-' . $_id . $_coreHelper->getRandomString(20); ?>
            <a href="#" id="<?php echo($popupId);?>" class="switch" gumby-trigger="#map-popup"><?php echo $this->__('Click for price'); ?></a>
            <script type="text/javascript">
                Event.observe(window, 'load', function() {
                    var priceElement = $("<?php echo $priceElementId ?>"),
                        realPrice = <?php echo $this->getRealPriceJs($_product) ?>,
                        priceHtml = realPrice.stripScripts();

                    priceElement.innerHTML = priceHtml;
                    realPrice.evalScripts();
                    var originalOptionPriceReload;
                    if (typeof(optionsPrice) != 'undefined' && optionsPrice && optionsPrice.reload) {
                        originalOptionPriceReload = optionsPrice.reload;
                        Product.OptionsPrice.prototype.reload = function() {
                            if (originalOptionPriceReload) {
                                originalOptionPriceReload.call(this);
                            }
                            if ($('<?php echo $popupId ?>') == Catalog.Map.active) {
                                Element.update(
                                    $('map-popup-price'),
                                    $("<?php echo $priceElementId ?>").innerHTML
                                );
                            }
                        }
                        optionsPrice.reload();
                    }
                });

                Catalog.Map.addHelpLink(
                    $('<?php echo $popupId ?>'),
                    "<?php echo $_product->getName() ?>",
                    $("<?php echo $priceElementId ?>"),
                    '<?php echo $_msrpPrice ?>',
                    "<?php echo $_product->isSalable() ? $_product->getAddToCartUrl() : '' ?>"
                );
            </script>
        <?php else: ?>
            <span class="msrp-price-hide-message">
                <?php echo $_catalogHelper->getMsrpPriceMessage($_product) ?>
            </span>
        <?php endif; ?>

        <?php $helpLinkId = 'msrp-help-' . $_id . $_coreHelper->getRandomString(20); ?>
        <a href="#" id="<?php echo($helpLinkId);?>" class="switch" gumby-trigger="#map-popup"><?php echo $this->__("What&#39;s this?"); ?></a>
        <script type="text/javascript">
            Catalog.Map.addHelpLink(
                $('<?php echo $helpLinkId ?>'),
                "<?php echo $this->__("What&#39;s this?"); ?>"
            );
        </script>
    </div>
