<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<?php if ($this->getQuote()->hasVirtualItems()): ?>
    <div class="col2-set">
        <h2 class="legend"><?php echo $this->__('Other Items in Your Order') ?></h2>
        <div class="col-1 col-narrow"></div>
        <div class="col-2 col-wide">
            <h3><?php echo $this->__('Items') ?> <span class="separator">|</span> <a href="<?php echo $this->getVirtualProductEditUrl() ?>"><?php echo $this->__('Edit Items') ?></a></h3>
            <div class="data-table" id="unavailable-shipping-table">
                <div class="row shaded">
                    <div class="ten columns">
                        <h4><?php echo $this->__('Product Name') ?></h4>
                    </div>
                    <div class="two columns field a-center">
                        <h4><?php echo $this->__('Qty') ?></h4>
                    </div>
                </div>
                <div>
                <?php foreach ($this->getVirtualQuoteItems() as $_item): ?>
                    <div class="row">
                        <div class="ten columns">
                            <?php echo $this->getItemHtml($_item) ?>
                        </div>
                        <div class="two columns a-center">
                            <?php echo $_item->getQty() ?>
                        </div>
                    </div>
                <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
