<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<?php
/**
 * @see Mage_Page_Block_Html_CookieNotice
 */
?>
<?php if (Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
<div class="global-site-notice notice-cookie" id="notice-cookie-block">
    <div class="notice-inner">
        <div class="notice-text"><?php echo $this->getCookieRestrictionBlockContent(); ?></div>
        <div class="actions">
            <div class="pretty medium info btn"><button class="button" onclick="allowSaveCookie()"><?php echo $this->__('Allow');?></button></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    /* <![CDATA[ */
    function allowSaveCookie() {
        Mage.Cookies.set('<?php echo Mage_Core_Helper_Cookie::IS_USER_ALLOWED_SAVE_COOKIE; ?>', '<?php echo Mage::helper('core/cookie')->getAcceptedSaveCookiesWebsiteIds()?>', new Date(new Date().getTime() + <?php echo Mage::helper('core/cookie')->getCookieRestrictionLifetime() ?> * 1000));
        if (Mage.Cookies.get('<?php echo Mage_Core_Helper_Cookie::IS_USER_ALLOWED_SAVE_COOKIE; ?>')) {
            window.location.reload();
        } else {
            window.location.href = '<?php echo Mage::getUrl('cms/index/noCookies')?>';
        }
    }
    $('notice-cookie-block').show();
    /* ]]> */
</script>
<?php endif; ?>


