<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */

/**
 * Authorize confirmation simple template
 *
 * @var $this Mage_Oauth_Block_AuthorizeBaseAbstract
 */
?>
<div class="login-container">
    <div class="login-box">
        <div class="page-title">
            <h1><?php echo $this->__('Confirmation Of Authorization') ?></h1>
        </div>
        <div class="form-box">
            <?php echo $this->getMessagesBlock()->toHtml() ?>
            <?php if ($this->getVerifier()): ?>
                <h2><?php echo $this->__('Authorization confirmed') ?></h2>
                <p><?php echo $this->__('Give the verifier code to application administrator') ?></p>
                <p style="font-size: 14px;"><?php echo $this->__('Verifier code: %s', $this->getVerifier()) ?></p>
            <?php endif; ?>
            <div class="pretty small info btn"><button type="submit" class="button" onclick="window.close();" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></button></div>
        </div>
    </div>
</div>
