<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */

/**
 * Authorize rejection simple template
 *
 * @var $this Mage_Oauth_Block_AuthorizeBaseAbstract
 */
?>
<div class="login-container">
    <div class="login-box">
        <div class="page-title">
            <h1><?php echo $this->__('Rejection Of Authorization') ?></h1>
        </div>
        <div class="form-box">
            <div id="messages">
                <?php echo $this->getMessagesBlock()->toHtml() ?>
            </div>
            <div class="pretty small info btn"><button type="submit" class="button" onclick="window.close();" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></button></div>
        </div>
    </div>
</div>
