<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
    <h1><?php echo $this->__('My Product Reviews') ?></h1>
</div>
<?php if( $this->getCollection() && $this->count()): ?>
    <?php /*
    <?php echo $this->getToolbarHtml() ?>
    */ ?>
        <?php foreach ($this->getCollection() as $_review): ?>
        <div>
            <h2 class="product-name"><a href="<?php echo $this->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->escapeHtml($_review->getName()) ?></a></h2>
            <?php if($_review->getSum()): ?>
                <div class="rating-box">
                    <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                </div>
            <?php endif; ?>
            <p><?php echo $this->helper('review')->getDetailHtml($_review->getDetail()) ?></p>
            <p><?php echo $this->__('Reviewed on:') ?>&nbsp;<span class="nobr"><?php echo $this->dateFormat($_review->getReviewCreatedAt()); ?></span></p>
            <a href="<?php echo $this->getReviewLink() ?>id/<?php echo $_review->getReviewId() ?>" class="nobr"><?php echo $this->__('View Details') ?></a>
        </div>
        <hr />
        <?php endforeach; ?>
    <?php if($this->count()>10): ?>
        <?php echo $this->getToolbarHtml() ?>
    <?php endif; ?> 
<?php else: ?>
    <p><?php echo $this->__('You have submitted no reviews.') ?></p>
<?php endif; ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
