<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
/** @var $this Mage_Sales_Block_Widget_Guest_Form */
?>
<?php if ($this->isEnable()): ?>
    <div class="widget">
        <div class="block block-gr-search">
            <div class="block-title">
                <strong>
                    <span><?php echo $this->__('Orders and Returns') ?></span>
                </strong>
            </div>
            <div class="block-content">
               <form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
                   <ul class="form-alt">
                       <li class="field">
                           <label class="required"><?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
                           <div class="input-box">
                            <div class="field">
                                <div class="picker">
                                 <select name="oar_type" id="quick_search_type_id" class="select" title="" onchange="showIdentifyBlock(this.value);">
                                     <option value="email">Email Address</option>
                                     <option value="zip">ZIP Code</option>
                                 </select>
                                </div>
                            </div>
                           </div>
                       </li>
                       <li class="field">
                           <?php /*
                           <label for="oar_order_id" class="required"><?php echo Mage::helper('sales')->__('Order ID') ?> <em>*</em></label>
                           */ ?>
                           <div class="input-box">
                               <input type="text" class="text input narrow input-text required-entry" id="oar_order_id" name="oar_order_id"  autocomplete="off" placeholder="<?php echo Mage::helper('sales')->__('Order ID') ?>" />
                           </div>
                       </li>
                       <li class="field">
                           <?php /*
                           <label for="oar_billing_lastname" class="required"><?php echo Mage::helper('sales')->__('Billing Last Name') ?> <em>*</em></label>
                           */ ?>
                           <div class="input-box">
                               <input type="text" class="text input narrow input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname" autocomplete="off" placeholder="<?php echo Mage::helper('sales')->__('Billing Last Name') ?>" />
                           </div>
                       </li>
                       <li class="field" id="oar-email">
                           <?php /*
                           <label for="oar_email" class="required"><?php echo Mage::helper('sales')->__('Email Address') ?> <em>*</em></label>
                           */ ?>
                           <div class="input-box">
                               <input type="text" class="text input narrow input-text validate-email required-entry" id="oar_email" name="oar_email" autocomplete="off" placeholder="<?php echo Mage::helper('sales')->__('Email Address') ?>" />
                           </div>
                       </li>
                       <li class="field" id="oar-zip" style="display:none;">
                           <?php /*
                           <label for="oar_zip" class="required"><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?> <em>*</em></label>
                           */ ?>
                           <div class="input-box">
                               <input type="text" class="text input narrow input-text required-entry" id="oar_zip" name="oar_zip" placeholder="<?php echo Mage::helper('sales')->__('Billing ZIP Code') ?>" />
                           </div>
                       </li>
                   </ul>
                   <div class="actions">
                      <div class="pretty medium info btn"><button type="submit" title="Continue" class="button"><?php echo Mage::helper('sales')->__('Continue') ?></button></div>
                   </div>
               </form>
            </div>
        </div>
    </div>
<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>
</script>
<?php endif; ?>
