<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="field add-to-cart f-left">
        <?php if(!$_product->isGrouped()): ?>
        <label class="inline" for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="xnarrow text input input-text qty" />
        <?php endif; ?>
        <div class="pretty medium primary btn"><button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><i class="icon-basket"></i><?php echo $buttonTitle ?></div>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
