<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */

/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()): ?>

                <table class="striped rounded data-table" id="product-attribute-specs-table">
                    <caption><?php echo $this->__('Additional Information') ?></caption>
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($_additional as $_data): ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($this->__($_data['label'])) ?></td>
                            <td><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
<?php endif;?>
