<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<div class="form-add">
    <h2><?php echo $this->__('Write Your Own Review') ?></h2>
    <?php if ($this->getAllowWriteReviewFlag()): ?>
    <form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <fieldset>
            <?php echo $this->getChildHtml('form_fields_before')?>
            <h3><?php echo $this->__("You're reviewing:"); ?> <span><?php echo $this->escapeHtml($this->getProductInfo()->getName()) ?></span></h3>
            <?php if( $this->getRatings() && $this->getRatings()->getSize()): ?>
                <span id="input-message-box"></span>
                <table class="data-table" id="product-review-table">
                    <col />
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                    <thead>
                        <tr>
                            <th><?php echo $this->__('How do you rate this product?') ?><?php /*<em class="required">*</em>*/ ?></th>
                            <th><span class="nobr"><?php echo $this->__('1 star') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('2 stars') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('3 stars') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('4 stars') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('5 stars') ?></span></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->getRatings() as $_rating): ?>
                        <tr class="field">
                            <td><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></td>
                        <?php foreach ($_rating->getOptions() as $_option): ?>
                            <td class="radio value a-center"><input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio" /><span></span></td>
                        <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                <script type="text/javascript">decorateTable('product-review-table')</script>
            <?php endif; ?>
                <ul class="form-list">
                    <li class="field">
                        <?php /*
                        <label for="nickname_field" class="inline required"><em>*</em><?php echo $this->__('Nickname') ?></label>
                        */ ?>    
                        <input type="text" name="nickname" id="nickname_field" class="normal text input input-text required-entry" value="<?php echo $this->escapeHtml($data->getNickname()) ?>" placeholder="<?php echo $this->__('Nickname') ?>" />
                    </li>
                    <li class="field">
                        <?php /*
                        <label for="summary_field" class="inline required"><em>*</em><?php echo $this->__('Summary of Your Review') ?></label>
                        */ ?>
                        <input type="text" name="title" id="summary_field" class="wide text input input-text required-entry" value="<?php echo $this->escapeHtml($data->getTitle()) ?>" placeholder="<?php echo $this->__('Summary of Your Review') ?>" />
                    </li>
                    <li class="field">
                        <?php /*
                        <label for="review_field" class="inline required"><em>*</em><?php echo $this->__('Review') ?></label>
                        */ ?>
                        <textarea name="detail" id="review_field" cols="5" rows="3" class="input textarea required-entry" placeholder="<?php echo $this->__('Review') ?>"><?php echo $this->escapeHtml($data->getDetail()) ?></textarea>
                    </li>
                </ul>
            </fieldset>
            <div class="buttons-set">
                <div class="pretty medium info btn"><button type="submit" title="<?php echo $this->__('Submit Review') ?>" class="button"><?php echo $this->__('Submit Review') ?></button></div>
            </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('review-form');
        Validation.addAllThese(
        [
               ['validate-rating', '<?php echo $this->__('Please select one of each of the ratings above') ?>', function(v) {
                    var trs = $('product-review-table').select('tr');
                    var inputs;
                    var error = 1;

                    for( var j=0; j < trs.length; j++ ) {
                        var tr = trs[j];
                        if( j > 0 ) {
                            inputs = tr.select('input');

                            for( i in inputs ) {
                                if( inputs[i].checked == true ) {
                                    error = 0;
                                }
                            }

                            if( error == 1 ) {
                                return false;
                            } else {
                                error = 1;
                            }
                        }
                    }
                    return true;
                }]
        ]
        );
    //]]>
    </script>
    <?php else: ?>
    <p class="review-nologged" id="review-form">
        <?php echo $this->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
    </p>
    <?php endif ?>
</div>
