<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<?php /* @var $this Mage_Sales_Block_Payment_Form_Billing_Agreement */?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_ba_agreement_id" class="required"><em>*</em><?php echo $this->__('Billing Agreement') ?></label>
        <div class="input-box">
            <div class="field">
                <div class="picker">
                    <select id="<?php echo $_code ?>_ba_agreement_id" name="payment[<?php echo $this->getTransportName(); ?>]" class="required-entry">
                        <option value=""><?php echo $this->__('-- Please Select Billing Agreement--') ?></option>
                    <?php foreach ($this->getBillingAgreements() as $id => $referenceId): ?>
                        <option value="<?php echo $id ?>"><?php echo $this->escapeHtml($referenceId) ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </div>
        </div>
    </li>
</ul>
