<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<div class="block block-tags">
    <div class="block-title">
        <strong><span><?php echo $this->__('Popular Tags'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="tags-list">
            <?php foreach ($this->getTags() as $_tag): ?>
                <li><a rel="tag" href="<?php echo $_tag->getTaggedProductsUrl() ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->escapeHtml($_tag->getName()) ?></a></li>
            <?php endforeach; ?>
        </ul>
        <div class="actions">
            <a href="<?php echo $this->getUrl('tag/list') ?>"><?php echo $this->__('View All Tags') ?></a>
        </div>
    </div>
</div>
