<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
/* @var $this Mage_Customer_Block_Widget_Name */
?>
<div class="<?php echo $this->getContainerClassName()?>">
<?php if ($this->showPrefix()): ?>
    <div class="field name-prefix">
        <?php /*
        <label for="<?php echo $this->getFieldId('prefix')?>" class="inline <?php if ($this->isPrefixRequired()) echo 'required' ?>"><?php if ($this->isPrefixRequired()) echo '<em>*</em>' ?><?php echo $this->getStoreLabel('prefix') ?></label>
        */ ?>
        <?php if ($this->getPrefixOptions() === false): ?>
            <input type="text" id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" value="<?php echo $this->escapeHtml($this->getObject()->getPrefix()) ?>" title="<?php echo $this->getStoreLabel('prefix') ?>" class="xnarrow text input input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('prefix') ?>" placeholder="<?php echo $this->getStoreLabel('prefix') ?>" <?php echo $this->getFieldParams() ?> />
        <?php else: ?>
            <div class="field">
                <div class="picker">
                    <select id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" title="<?php echo $this->getStoreLabel('prefix') ?>" class="<?php echo $this->helper('customer/address')->getAttributeValidationClass('prefix') ?>" <?php echo $this->getFieldParams() ?>>
                        <option value="#" disabled selected="selected"><?php echo $this->__('Prefix') ?></option>
                    <?php foreach ($this->getPrefixOptions() as $_option): ?>
                        <?php if ($_option['value']!='') { ?>
                        <option value="<?php echo $_option?>"><?php echo $this->__($_option)?></option>
                        <?php } ?>
                    <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
    <div class="field name-firstname">
        <?php /*
        <label for="<?php echo $this->getFieldId('firstname')?>" class="inline required"><em>*</em><?php echo $this->getStoreLabel('firstname') ?></label>
        */ ?>
        <input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo $this->escapeHtml($this->getObject()->getFirstname()) ?>" title="<?php echo $this->getStoreLabel('firstname') ?>" maxlength="255" class="narrow text input input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('firstname') ?>" placeholder="<?php echo $this->getStoreLabel('firstname') ?>" <?php echo $this->getFieldParams() ?> />
    </div>
<?php if ($this->showMiddlename()): ?>
<?php $isMiddlenameRequired = $this->isMiddlenameRequired(); ?>
    <div class="field name-middlename">
        <?php /*
        <label for="<?php echo $this->getFieldId('middlename')?>" class="inline <?php echo $isMiddlenameRequired ? 'required' : '' ?>"><?php echo $isMiddlenameRequired ? '<em>*</em>' : '' ?><?php echo $this->getStoreLabel('middlename') ?></label>
        */ ?>
        <input type="text" id="<?php echo $this->getFieldId('middlename')?>" name="<?php echo $this->getFieldName('middlename')?>" value="<?php echo $this->escapeHtml($this->getObject()->getMiddlename()) ?>" title="<?php echo $this->getStoreLabel('middlename') ?>" class="narrow text input input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('middlename') ?>" placeholder="<?php echo $this->getStoreLabel('middlename') ?>" <?php echo $this->getFieldParams() ?> />
    </div>
<?php endif; ?>
    <div class="field name-lastname">
        <?php /*
        <label for="<?php echo $this->getFieldId('lastname')?>" class="inline required"><em>*</em><?php echo $this->getStoreLabel('lastname') ?></label>
        */ ?>
        <input type="text" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php echo $this->escapeHtml($this->getObject()->getLastname()) ?>" title="<?php echo $this->getStoreLabel('lastname') ?>" maxlength="255" class="narrow text input input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('lastname') ?>" placeholder="<?php echo $this->getStoreLabel('lastname') ?>" <?php echo $this->getFieldParams() ?> />
    </div>
<?php if ($this->showSuffix()): ?>
    <div class="field name-suffix">
        <?php /*
        <label for="<?php echo $this->getFieldId('suffix')?>" class="inline <?php if ($this->isSuffixRequired()) echo 'required' ?>"><?php if ($this->isSuffixRequired()) echo '<em>*</em>' ?><?php echo $this->getStoreLabel('suffix') ?></label>
        */ ?>
        <?php if ($this->getSuffixOptions() === false): ?>
            <input type="text" id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" value="<?php echo $this->escapeHtml($this->getObject()->getSuffix()) ?>" title="<?php echo $this->getStoreLabel('suffix') ?>" class="xnarrow text input input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('suffix') ?>" placeholder="<?php echo $this->getStoreLabel('suffix') ?>" <?php echo $this->getFieldParams() ?> />
        <?php else: ?>
            <div class="field">
                <div class="picker">
                    <select id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" title="<?php echo $this->getStoreLabel('suffix') ?>" class="<?php echo $this->helper('customer/address')->getAttributeValidationClass('suffix') ?>" <?php echo $this->getFieldParams() ?>>
                        <option value="#" disabled selected="selected"><?php echo $this->__('Suffix') ?></option>
                    <?php foreach ($this->getSuffixOptions() as $_option): ?>
                        <?php if ($_option['value']!='') { ?>
                        <option value="<?php echo $_option?>"><?php echo $this->__($_option)?></option>
                        <?php } ?>
                    <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
</div>
