<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Change Account Password') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $action ?>" method="post" id="form-validate">
<div class="fieldset">
    <h2 class="legend"><?php echo $this->__('Change Account Password') ?></h2>
    <ul class="form-list">
        <li>
            <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
            <div class="input-box">
                <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text required-entry" name="current_password" id="current_password" />
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                <div class="input-box">
                    <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text required-entry validate-password" name="password" id="password" />
                </div>
            </div>
            <div class="field">
                <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                <div class="input-box">
                    <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                </div>
            </div>
        </li>
    </ul>
</div>
<div class="buttons-set">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <div class="pretty medium secondary btn"><button type="submit" title="<?php echo $this->__('Save Password') ?>" class="button"><?php echo $this->__('Save Password') ?></button></div>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate');
//]]>
</script>
