<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Edit Account Information') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" autocomplete="off">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li class="field">
                <?php /*
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                */ ?>
                <input type="text" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="normal text input input-text required-entry validate-email" placeholder="<?php echo $this->__('Email Address') ?>" />
            </li>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
        <?php endif ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
        <?php endif ?>
            <li class="field control">
                <label class="checkbox" for="change_password">
                    <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    <span onclick="click_option('change_password')"></span>
                    <p onclick="click_option('change_password')"><?php echo $this->__('Change Password') ?></p>
                </label>
            </li>
        </ul>
    </div>
    <div class="fieldset" style="display:none;">
        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
        <ul class="form-list">
            <li class="field">
                <?php /*
                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                */ ?>
                <div>
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="normal text input input-text" name="current_password" id="current_password" placeholder="<?php echo $this->__('Current Password') ?>" />
                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                    <input type="text" class="hide input-text no-display" name="dummy" id="dummy" />
                </div>
            </li>
            <li class="field">
                <?php /*
                <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                */ ?>
                <div class="input-box">
                    <input type="password" title="<?php echo $this->__('New Password') ?>" class="normal text input input-text validate-password" name="password" id="password" placeholder="<?php echo $this->__('New Password') ?>" />
                </div>
            </li>
            <li class="field">
                <?php /*
                <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                */ ?>
                <div class="input-box">
                    <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="normal text input input-text validate-cpassword" name="confirmation" id="confirmation" placeholder="<?php echo $this->__('Confirm New Password') ?>" />
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <?php /*
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        */ ?>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <div class="pretty medium info btn"><button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><?php echo $this->__('Save') ?></button></div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
