<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li class="field">
                <?php /*
                <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                */ ?>
                <input type="text" name="email" alt="email" id="email_address" class="no-margin normal text input input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" placeholder="<?php echo $this->__('Email Address') ?>" />
                <div class="pretty medium info btn"><button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button></div>
            </li>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
    </div>
    <div class="buttons-set">
        <?php /*
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        */ ?>
        <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
