<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<div class="row">
    <div class="account-login">
        <div class="page-title">
            <h1><?php echo $this->__('Login or Create an Account') ?></h1>
        </div>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.form.login.extra')?>
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <div class="row">
                <div class="six columns new-users">
                    <div class="content">
                        <h2><?php echo $this->__('New Customers') ?></h2>
                        <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                    </div>
                    <div class="buttons-set">
                        <div class="pretty medium info btn f-right"><button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';"><?php echo $this->__('Create an Account') ?></button></div>
                    </div>                
                </div>
                <div class="six columns registered-users">
                    <div class="content">
                        <h2><?php echo $this->__('Registered Customers') ?></h2>
                        <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                        <ul class="form-list">
                            <li class="field">
                                <?php /*
                                <label for="email" class="inline required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                */ ?>
                                <input type="email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="email wide text input input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" placeholder="Email Address" />
                            </li>
                            <li class="field">
                                <?php /*
                                <label for="pass" class="inline required"><em>*</em><?php echo $this->__('Password') ?></label>
                                */ ?>
                                <input type="password" name="login[password]" class="password wide input input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" placeholder="Password input" />
                            </li>                            
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                        </ul>
                        <?php /*
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        */ ?>
                    </div>
                    <div class="buttons-set">
                        <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                        <div class="pretty medium info btn f-right"><button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><?php echo $this->__('Login') ?></button></div>
                    </div>                
                </div>
            </div>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var dataForm = new VarienForm('login-form', true);
        //]]>
        </script>
    </div>
</div>