<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<?php 
/**
 * Mustishipping state
 * 
 * @see Mage_Checkout_Block_Multishipping_State
 */
?>
<div gumby-comment-media="(min-width: 768px)">
	<!--
	<ul class="checkout-progress" id="checkout-progress-state">
	<?php foreach ($this->getSteps() as $_step): ?>
	    <li title="<?php echo $_step->getLabel() ?>"<?php if($_step->getIsActive()): ?> class="active"<?php endif; ?>><span><?php echo $_step->getLabel() ?></span></li>
	<?php endforeach; ?>
	</ul>
	<script type="text/javascript">decorateGeneric($$('#checkout-progress-state li'), ['first','last']);</script>
	-->
</div>

