<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */

/**
 * Customer login form template
 *
 * @var $this Mage_Oauth_Block_Authorize
 */

$rejectJs = "document.location.href='{$this->getRejectUrl()}';";
?>
<div class="account-login">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php if (!$this->getHasException()): ?>
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
            <div class="col1-set">
                <div class="col-1 registered-users">
                    <div class="content" style="margin: 0 auto; padding-bottom: 13px;">
                        <h2><?php echo $this->__('Log in as a customer') ?></h2>
                        <p class="description"><?php echo $this->__('Log in to use <strong>%s</strong>', $this->getConsumer()->getName()) ?></p>
                        <ul class="form-list">
                            <li>
                                <label for="email"><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                                </div>
                            </li>
                            <li>
                                <label for="pass"><?php echo $this->__('Password') ?></label>
                                <div class="input-box">
                                    <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                                </div>
                            </li>
                        </ul>
                        <div class="buttons-set" style="margin-top: 20px; padding: 0;">

                            <div class="pretty medium info btn f-right"><button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><?php echo $this->__('Login') ?></button></div>
                            <div class="pretty medium info btn"><button type="submit" class="button" onclick="<?php echo $rejectJs; ?>"
                                    title="<?php echo $this->__('Reject') ?>" name="send"><?php echo $this->__('Reject') ?></button></div>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" name="oauth_token" value="<?php echo $this->escapeHtml($this->getToken()) ?>"/>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var dataForm = new VarienForm('login-form', true);
        //]]>
        </script>
    <?php endif; ?>
</div>
