<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li class="field">
    	<?php /*
        <label for="po_number" class="required"><em>*</em><?php echo $this->__('Purchase Order Number') ?></label>
        */ ?>
        <input type="text" id="po_number" name="payment[po_number]" title="<?php echo $this->__('Purchase Order Number') ?>" class="input text normal input-text required-entry" value="<?php echo $this->escapeHtml($this->getInfoData('po_number')) ?>" placeholder="<?php echo $this->__('Purchase Order Number') ?>" />
    </li>
</ul>
