<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */
?>
<?php
/**
 * "Remember Me" popup template (when click on "What's this?")
 *
 */
/** @var $this Mage_Core_Block_Template */
?>

<div class="remember-me-popup modal" id="remember-me-popup">
    <div class="content">
        <div class="remember-me-popup-head">
            <a href="#" class="close switch remember-me-popup-close f-right" gumby-trigger="|#remember-me-popup" title="<?php echo $this->__('Close') ?>"><i class="icon-cancel"></i></a>
            <h3><?php echo $this->__('What\'s this?') ?></h3>
        </div>
        <div class="remember-me-popup-body">
            <p>Checking &quot;Remember Me&quot; will let you access your shopping cart on this computer when you are logged out</p>
        </div>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    document.observe("dom:loaded", function() {
        new Insertion.Bottom($$('body')[0], $('remember-me-popup'));
    });
//]]>
</script>