<?php
/**
 * package      frontlinedev
 * theme        gumby
 * developer    Jason Tipton - Frontlinedev.com
 * contact      jason@frontlinedev.com
 */

?>
		<a href="<?php echo $this->getItemRemoveUrl($this->getItem()); ?>" onclick="return confirmRemoveWishlistItem();" title="<?php echo $this->__('Remove Item') ?>"
	    class="btn-remove btn-remove2"><i class="icon-cancel-squared"></i></a>
	</div><?php /* end three columns */ ?>
</div><?php /* end row */ ?>